config/routes.rb
Rails.application.routes.draw do
  pages = %w(about terms privacy_policy)

  resources :stories, except: :show, shallow: true do
    resources :chapters, except: [:index, :show], shallow: true do
      resources :parts, except: :index, shallow: true do
        resources :posts, except: [:show, :index] 
      end  
    end
    resources :characters, except: :show
  end

  root 'pages#index'
  pages.each do |page|
    get "#{page}", to: "pages##{page}"
  end
  resources :pages, only: [:edit, :update, :show]
  post 'tinymce_assets', to: 'tinymce_assets#create'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :settings, only: [:new, :create, :edit, :update]
  # get 'import', to: 'import#index'
  # post 'process', to: 'import#add_data'

end

app/models/part.rb
class Part < ApplicationRecord
  belongs_to :chapter
  has_many :posts, dependent: :destroy
  accepts_nested_attributes_for :posts, allow_destroy: true

  validates :title, presence: true
  validates :chat_title, presence: true
  validates :content, presence: true
  validates :publish_at, presence: true, on_or_after_today: true, on: :create
  validates :sort_order, numericality: true, uniqueness: { scope: :chapter_id, message: "This sort # has already been chosen." }

  default_scope { order(sort_order: :asc) }

  scope :published_part, -> (id) { joins(:chapter).where(
    "parts.id = :id AND stories.published = :published AND parts.published = :published AND parts.publish_at <= :today", 
    {id: id, published: true, today: Date.today}) }
    
  scope :published_parts, ->(story_id) { joins(:chapter).where( 
    "chapters.story_id = :story_id AND parts.published = :published AND parts.publish_at <= :today", 
    {story_id: story_id, published: true, today: Date.today} ) }

  def self.next_part( chapter_id, sort_order, admin ) 
    if admin
      where( "parts.chapter_id = :chapter_id AND parts.sort_order > :sort_order", 
        {chapter_id: chapter_id, sort_order: sort_order} ).limit(1)
    else
      where( "parts.chapter_id = :chapter_id AND parts.sort_order > :sort_order AND parts.published = :published AND parts.publish_at <= :today", 
        {chapter_id: chapter_id, sort_order: sort_order, published: true, today: Date.today} ).limit(1)
    end
  end
  
  def self.first_part( chapter_id, admin )
    if admin
      where( "parts.chapter_id = :chapter_id", {chapter_id: chapter_id} ).first
    else
      where( "parts.chapter_id = :chapter_id AND parts.published = :published AND parts.publish_at <= :today",
        {chapter_id: chapter_id, published: true, today: Date.today} ).first
    end
  end

  def self.last_part( chapter_id, admin )
    if admin
      where( "parts.chapter_id = :chapter_id", {chapter_id: chapter_id} ).last
    else
      where( "parts.chapter_id = :chapter_id AND parts.published = :published AND parts.publish_at <= :today", 
        {chapter_id: chapter_id, published: true, today: Date.today} ).last
    end
  end
          
  def self.prev_part( chapter_id, sort_order, admin )
    if admin
      unscope(:order).where( "parts.chapter_id = :chapter_id AND parts.sort_order < :sort_order", 
        {chapter_id: chapter_id, sort_order: sort_order} ).order(sort_order: :desc).limit(1)
    else
      unscope(:order).where( 
        "parts.chapter_id = :chapter_id AND parts.sort_order < :sort_order AND parts.published = :published AND parts.publish_at <= :today", 
        {chapter_id: chapter_id, sort_order: sort_order, published: true, today: Date.today} ).order(sort_order: :desc).limit(1)
    end
  end
  
end

app/controllers/parts_controller.rb
class PartsController < ApplicationController
  before_action :require_admin_user, except: [:show]
  before_action :set_chapter, only: [:new, :create]
  before_action :set_part, only: [:edit, :update, :destroy]

  def show
    @part = Part.find(params[:id])
    if !admin_user? && @part.present?
      if !@part.published && @part.publish_at >= Date.today
        @part = Part.published_parts(@part.chapter.story_id).take
      end 
    end
    set_parents
  end

  def new
    @part = @chapter.parts.new
  end

  def edit
  end

  def create
    @part = @chapter.parts.build( part_params )
    if @part.save
      flash[:notice] = "Part was successfully created"
      redirect_to part_path(@part)
    else
      render :new
    end
  end

  def update
    if @part.update( part_params )
      flash[:notice] = "Part was successfully updated"
      redirect_to part_path(@part)
    else
      render :edit
    end
  end

  def destroy
    @part.destroy
    flash[:notice] = "Part was successfully deleted"
    redirect_to back_to_story_path(@story.id)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chapter
      @chapter = Chapter.find(params[:chapter_id])
      @story = Story.find(@chapter.story_id)
    end

    def set_parents
      if @part.present?
        @chapter = Chapter.find(@part.chapter_id)
        @story = Story.find(@chapter.story_id)    
        cookie_name = "story_#{@story.id}"
        cookies[cookie_name] = @part.id
      else
        redirect_to stories_path
      end
    end

    def set_part
      @part = Part.find(params[:id])
      set_parents
    end

    # Only allow a list of trusted parameters through.
    def part_params
      params.require(:part).permit(:title, :subtitle, :chat_title, :sort_order, :published, :content, :publish_at)
    end
end

app/helpers/parts_helper.rb
module PartsHelper

  def get_next_part(current_part)
    next_part = Part.next_part( current_part.chapter_id, current_part.sort_order, admin_user? ).take
    if !next_part.present?
      next_chapter = Chapter.next_chapter(current_part.chapter.story_id, current_part.chapter.sort_order).take  
      begin 
        if next_chapter.present?
          next_part = Part.first_part(next_chapter.id, admin_user?)                    
        end
        if !next_part.present? && next_chapter.present?
          next_chapter = Chapter.next_chapter(current_part.chapter.story_id, next_chapter.sort_order).take
        end  
      end until next_part.present? || !next_chapter.present?
    end 
    next_part
  end

  def get_prev_part(current_part)
    prev_part = Part.prev_part(current_part.chapter_id, current_part.sort_order, admin_user?).take
    if !prev_part.present?
      prev_chapter = Chapter.prev_chapter(current_part.chapter.story_id, current_part.chapter.sort_order ).take
      begin  
        if prev_chapter.present?
          prev_part = Part.last_part(prev_chapter.id, admin_user?)
        end
        if !prev_part.present? && prev_chapter.present?
          prev_chapter = Chapter.prev_chapter(current_part.chapter.story_id, prev_chapter.sort_order ).take
        end
      end until prev_part.present? || !prev_chapter.present?
    end 
    prev_part
  end

end

app/views/parts/_admin_buttons.html.erb
<%# edit_url: delete_url: %>
<div class="btn-group">
  <%= link_to edit_url, class: "btn btn-sm btn-outline-dark" do %>
    <i class="bi bi-pencil pe-1"></i>Edit
  <% end %>
  <%= link_to delete_url, class: "btn btn-sm btn-outline-dark", 
      method: :delete, 
      data: { confirm: "Are you sure?" } do %>
    <i class="bi bi-trash pe-1"></i>Delete
  <% end %>
</div>

app/views/parts/_admin_status.html.erb
<%# resource: %>
<i class="bi bi-sort-numeric-down ps-1"></i>
<%= resource.sort_order %>
<% if !resource.published %>
  <i class="bi bi-asterisk ps-1"></i>
<% end %>
<% if resource.publish_at > Date.today %>
  <i class="bi bi-calendar ps-1"></i>
<% end %>

app/views/parts/_form.html.erb
<%= form_with(model: part, url: post_url) do |form| %>
  <%= render 'shared/error_messages', resource: part %>

   <div class="row justify-content-end">
   <div class="col-10">
      <div class="form-check form-switch">
        <%= form.check_box :published, 
                  class: "form-check-input", 
                  id: "flexSwitchCheckPublished" %>
        <%= form.label :published,  class: "form-check-label", 
                      for: "flexSwitchCheckPublished" %>        
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-2 d-flex align-items-center">
      <%= form.label :sort_order %>
    </div>
    <div class="col field form-group">
      <%= form.number_field :sort_order, class: "form-control" %>
    </div>
  </div>

  <div class="row pt-2">
    <div class="col-2 d-flex align-items-center">
      <%= form.label :publish_at %>
    </div>
    <div class="col field form-group">
      <%= form.date_field :publish_at, class: "form-control" %>
    </div>
  </div>
  <div class="row pt-2">
    <div class="col-2 d-flex align-items-center">
      <%= form.label :title %>
    </div>
    <div class="col field form-group">
      <%= form.text_field :title, class: "form-control" %>
    </div>
  </div>  
  <div class="row pt-2">
    <div class="col-2 d-flex align-items-center">
      <%= form.label :subtitle %>
    </div>
    <div class="col field form-group">
      <%= form.text_field :subtitle, class: "form-control" %>
    </div>
  </div>  
  <div class="row pt-2">
    <div class="col-2 d-flex align-items-center">
      <%= form.label :chat_title %>
    </div>
    <div class="col field form-group">
      <%= form.text_field :chat_title, class: "form-control" %>
    </div>
  </div>  
  <div class="row pt-2">
    <div class="col field form-group">
      <%= form.text_area :content, class: "tinymce" %>
      <%= tinymce %>
    </div>
  </div>  
  <div class="actions pt-2">
    <%= form.submit class: "btn btn-sm btn-outline-dark" %>
  </div>
<% end %>

app/views/parts/_next_link.html.erb
Next Part <i class="bi bi-caret-right-fill"></i>

app/views/parts/_next_prev.html.erb
<div class="row justify-content-center py-1">
  <div class="btn-group">

    <% prev_part = get_prev_part(part) %>
    <% if prev_part.present? %>
      <%= link_to part_path(prev_part), class: "btn btn-sm btn-outline-dark" do %>
        <%= render 'prev_link' %>
      <% end %>
    <% else %>
      <button type="button" class="btn btn-sm btn-outline-dark" disabled>
        <%= render 'prev_link' %>
      </button>
    <% end %>

    <% next_part = get_next_part(part) %>
    <% if next_part.present? %>
      <%= link_to part_path(next_part), class: "btn btn-sm btn-outline-dark" do %>
        <%= render 'next_link' %>
      <% end %>
    <% else %>
      <button type="button" class="btn btn-sm btn-outline-dark" disabled>
        <%= render 'next_link' %>
      </button>
    <% end %>

  </div>
</div>

app/views/parts/_prev_link.html.erb
<i class="bi bi-caret-left-fill"></i> Previous Part

app/views/parts/_sidebar.html.erb
<div id="sidebar" class="col-xs sidebar flex-shrink-0 p-3 scroll">
    <span class="fs-5 fw-semibold"> 
      <%= story.short_title %>
    </span>
    <% if admin_user? %>
      <%= link_to edit_story_path(story), class: "btn btn-sm btn-light"  do %>
        <i class="bi bi-pencil"></i>
      <% end %>
    <% end %>

  <ul class="list-unstyled ps-0">
    <% if admin_user? %>
      <li class="mb-1">
        <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#home-collapse" aria-expanded="false">
          Actions
        </button>
        <div class="collapse" id="home-collapse">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
            <li>
              <%= link_to story_characters_path(story), class: "link-dark rounded"  do %>
                <i class="bi bi-people pe-1"></i> Characters
              <% end %>
            </li>
            <li>
              <%= link_to new_story_chapter_path(story), 
              class: "#{request.path == new_story_chapter_path(story)  ? "link-dark rounded link-active" : "link-dark rounded"}"  do %>
                <i class="bi bi-folder-plus pe-1"></i> Add a Chapter
              <% end %>
            </li>
          </ul>
        </div>
      </li>
    <% end %>

    <% if story.chapters.present? %>
      <% story.chapters.each do |chapter| %>
        <li class="mb-1">
          <button class="btn btn-toggle align-items-center rounded collapsed" 
                    data-bs-toggle="collapse" 
                    data-bs-target="#dashboard-collapse-<%= chapter.id %>" 
                    aria-expanded="<%= @chapter.id == chapter.id %>">
            <%= chapter.title %>
          </button>
          <% if admin_user? %>
            <%= link_to edit_chapter_path(chapter), class: "btn btn-sm btn-light"  do %>
              <i class="bi bi-pencil"></i>
            <% end %>
          <% end %>          
          <div class="<%= @chapter.id == chapter.id ? "collapse show" : "collapse" %>" id="dashboard-collapse-<%= chapter.id %>">
            <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">

              <% if admin_user? %>
                <%= link_to new_chapter_part_path(chapter), class: "link-dark rounded" do %>
                  <i class="bi bi-file-earmark-plus pe-1"></i>Add a Part
                <% end %>
              <% end %>
              <% if chapter.parts.present? %>
                <% chapter.parts.each do |part| %>
                  <% if admin_user? || ( part.published && part.publish_at <= Date.today ) %>
                  <li>
                    <% if part.id == @part.id %>
                      <span class="btn-toggle-nav-text"><%= part.title %></span>
                    <% else %>
                      <%= link_to part_path(part), class: "link-dark rounded" do %>
                        <%= part.title %>
                      <% end %>
                    <% end %>
                    <% if admin_user? %>
                      <%= render 'admin_status', resource: part %>
                    <% end %>
                  </li>
                  <% end %>
                <% end %>
              <% end %>
            </ul>
          </div>
        </li>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/parts/edit.html.erb
<div class="container py-3">
  <div class="card mb-3 shadow-lg rounded border">
    <div class="card-body text-dark">
      <h4>Editing part for <%= @story.short_title %></h4>
      <%= render 'form', part: @part, post_url: part_path(@part) %>
      <div class="btn-group p-2">
        <%= link_to "Delete", part_path(@part), class: "btn btn-sm btn-outline-dark", 
                    method: :delete, 
                    data: { confirm: "Are you sure? This will delete ALL chats associated to this part too." } %>
        <%= link_to t('show_story'),back_to_story_path(@story.id), class: "btn btn-sm btn-outline-dark" %> 
      </div>
    </div>
  </div>
</div>

app/views/parts/new.html.erb
<div class="container py-3">
  <div class="card mb-3 shadow-lg rounded border">
    <div class="card-body text-dark">
      <h4>New part for <%= @story.short_title %></h4>
      <%= render 'form', part: @part, post_url: chapter_parts_path(@chapter) %>
      <div class="btn-group p-2">
        <%= link_to t('show_story'), back_to_story_path(@story.id), class: "btn btn-sm btn-outline-dark" %> 
      </div>
    </div>
  </div>
</div>

app/views/parts/show.html.erb
<% provide(:title, "#{@story.short_title} | #{@chapter.title} | #{@part.title}") %>
<div class="d-flex flex-row justify-content-center">
  <%= render 'sidebar', story: @story %>
  <div class="col-lg p-1" id="view_panel">
    <button id="sidebarCollapse" type="button" class="btn rounded-pill shadow-sm px-1 mb-2 sidebar-btn">
      <i id="sidebar_button_icon" class="bi bi-file-excel"></i><small class="p-1 text-uppercase font-weight-bold">
      Table of Contents</small>
    </button>
    <div class="album py-2">
      <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-2 g-3">
          <div id="story_col" class="container">            
            <div id="story_header" class="pb-1" style="width: 100%; float: none; margin-left: auto; margin-right: auto;">
              <% if @story.header_picture.present? %>
                <%= image_tag @story.header_picture_url, 
                        style: "width: 100%; height: 100%;" %>
              <% end %>
              <h4 class="part_story"><%= @story.long_title %></h4>
              <small><%= "#{@story.author} All rights reserved." %></small>
              <div class="row">
                <div class="col">
                  <h6><%= "#{@chapter.title} | #{@part.title}" %></h6>
                  <h6><%= @part.subtitle %></h6>
                </div>
                <% if admin_user? %>
                  <div class="col d-flex align-self-end align-items-end flex-column">
                    <div>
                      <%= render 'admin_status', resource: @part %>
                    </div>
                    <%= render 'admin_buttons', edit_url: edit_part_path(@part), delete_url: part_path(@part) %>
                  </div>
                <% end %>
              </div>
            </div>
          <!-- d-flex justify-content-between pt-1//-->
            <div id="story" class="container">
              <%= render 'next_prev', part: @part %>
              <% unless @part.content.blank? %>
                <%= @part.content.html_safe %>
              <% end %>  
              <%= render 'next_prev', part: @part %>
            </div>
          </div>          
          <div id="chat_col" class="container">
            <div id="chat_header" class="p-2">            
              <div class="row">
                <div class="col">
                  <strong>
                    <%= "#{@story.short_title} Chat" %><br/>
                    <%= @story.author %><br/>
                    <%= "#{@chapter.title} | #{@part.title}" %><br/>
                    <%= @part.chat_title %>
                  </strong>
                </div>
                <% if admin_user? %>
                  <div class="col d-flex align-self-end align-items-end flex-column">                  
                    <div class="btn-group">
                      <%= link_to new_part_post_path(@part), class: "btn btn-sm btn-outline-light" do %>
                        <i class="bi bi-pencil pe-1"></i>Add a Post
                      <% end %>
                    </div>                                      
                  </div>
                <% end %>
              </div>            
              <hr>
            </div>
            <div id="chat" class="container scroll">
              <% if @part.posts.present? %>
                <% @part.posts.each do |post| %>
                  <% if (post.published? && post.publish_at <= Date.today) || admin_user? %>
                    <div class="card mt-2">
                      <div class="card-body px-2 py-0">
                        <p class="card-text">
                          <div class="post_character pe-1">
                            <%= post.character.chat_name %> : 
                          </div>                          
                          <% unless post.message.blank? %>
                            <%= post.message.html_safe %>
                          <% end %>
                        </p>
                      </div>
                      <% if admin_user? %>
                        <div class="card-footer">
                          <%= render 'admin_buttons', edit_url: edit_post_path(post), delete_url: post_path(post) %>
                          <%= render 'admin_status', resource: post %>
                        </div>
                      <% end %>
                    </div>
                  <% end %>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>