config/routes.rb
Rails.application.routes.draw do
  pages = %w(about terms privacy_policy)

  resources :stories, except: :show, shallow: true do
    resources :chapters, except: [:index, :show], shallow: true do
      resources :parts, except: :index, shallow: true do
        resources :posts, except: [:show, :index] 
      end  
    end
    resources :characters, except: :show
  end

  root 'pages#index'
  pages.each do |page|
    get "#{page}", to: "pages##{page}"
  end
  resources :pages, only: [:edit, :update, :show]
  post 'tinymce_assets', to: 'tinymce_assets#create'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :settings, only: [:new, :create, :edit, :update]
  # get 'import', to: 'import#index'
  # post 'process', to: 'import#add_data'

end

app/models/character.rb
class Character < ApplicationRecord
  belongs_to :story
  has_many :posts, dependent: :destroy
  accepts_nested_attributes_for :posts, allow_destroy: true
  
  validates :chat_name, presence: true
  validates :sort_order, numericality: true

  default_scope { order(sort_order: :asc) }
  
  scope :from_story, ->(story_id) { joins(:story).where("stories.id = :id", {id: story_id}) }
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :require_admin_user
  before_action :set_story, only: [ :index, :new, :create ]
  before_action :set_character, only: [ :edit, :update, :destroy ]

  def index
    @characters = @story.characters
  end

  # def show
  # end

  def new
    @character = @story.characters.new
  end

  def edit
  end

  def create
    @character = @story.characters.build( character_params )
    if @character.save
      flash[:notice] = "Character was successfully created"
      redirect_to back_to_story_path(@story.id)
    else
      render :new
    end
  end

  def update
    if @character.update( character_params )
      flash[:notice] = "Character was successfully updated"
      redirect_to back_to_story_path(@story.id)
    else
      render :edit
    end
  end

  def destroy
    @character.destroy
    flash[:notice] = "Character was successfully deleted"
    redirect_to back_to_story_path(@story.id)
  end

  private
    def set_story
      @story = Story.find(params[:story_id])
    end

    def set_character
      @character = Character.find(params[:id])
      @story = Story.find(@character.story_id)
    end

    def character_params
      params.require(:character).permit(:full_name, :chat_name, :sort_order, :description)
    end
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/views/characters/_form.html.erb
<%= form_with(model: character, url: post_url) do |form| %>
  <%= render 'shared/error_messages', resource: character %>

  <div class="row">
    <div class="col-2 d-flex align-items-center">
      <%= form.label :sort_order %>
    </div>
    <div class="col field form-group">
      <%= form.number_field :sort_order, class: "form-control" %>
    </div>
  </div>

  <div class="row pt-2">
    <div class="col-2 d-flex align-items-center">
      <%= form.label :full_name %>
    </div>
    <div class="col field form-group">
      <%= form.text_field :full_name, class: "form-control" %>
    </div>
  </div>
  <div class="row pt-2">
    <div class="col-2 d-flex align-items-center">
      <%= form.label :chat_name %>
    </div>
    <div class="col field form-group">
      <%= form.text_field :chat_name, class: "form-control" %>
    </div>
  </div>  
  <div class="row pt-2">
    <div class="col-2 d-flex align-items-top">
      <%= form.label :description %>
    </div>
    <div class="col field form-group">
       <%= form.text_area :description, size: "70x5", class: "form-control" %>
    </div>
  </div>  
  <div class="actions pt-2">
    <%= form.submit class: "btn btn-sm btn-outline-dark" %>
  </div>
<% end %>

app/views/characters/edit.html.erb
<div class="container py-3">
  <div class="card mb-3 shadow-lg rounded border">
    <div class="card-body text-dark">
      <h4>Editing Character for <%= @story.short_title %></h4>
      <%= render 'form', character: @character, post_url: character_path(@character) %>
      <div class="btn-group p-2">
        <%= link_to t('show_story'), back_to_story_path(@story.id), class: "btn btn-sm btn-outline-dark" %>
        <%= link_to "All characters", story_characters_path(@story), class: "btn btn-sm btn-outline-dark" %> 
        <%= link_to "Delete", character_path(@character), class: "btn btn-sm btn-outline-dark", 
                    method: :delete, 
                    data: { confirm: "Are you sure? This will delete ALL chats this character posted." } %>
      </div>
    </div>
  </div>
</div>

app/views/characters/index.html.erb
<div class="container py-3">
  <div class="card mb-3 shadow-lg rounded border">
    <div class="card-body text-dark">
      <h4>Characters for <%= @story.short_title %></h4>


      <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">Order </th>
            <th scope="col">Name </th>
            <th scope="col">Post Name</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @story.characters.each do |character| %>
            <tr>
              <td><%= character.sort_order %></td>
              <td><%= character.full_name %></td>
              <td><%= character.chat_name %></td>
              <td>
                <%= link_to edit_character_path(character) do %>
                  <i class="bi bi-pencil"></i>
                <% end %>
                <%= link_to character_path(character), method: :delete, 
                              data: { confirm: 'Are you sure? This will delete ALL chats this character posted.' } do %>
                  <i class="bi bi-trash"></i>
                <% end %>
              </td>
            </tr>
          <% end %>

        </tbody>
      </table>


      <div class="btn-group p-2">
        <%= link_to t('show_story'), back_to_story_path(@story.id), class: "btn btn-sm btn-outline-dark" %> 
        <%= link_to 'New Character', new_story_character_path(@story), 
                                class: "btn btn-sm btn-outline-dark" %>
      </div>
    </div>
  </div>
</div>

app/views/characters/new.html.erb
<div class="container py-3">
  <div class="card mb-3 shadow-lg rounded border">
    <div class="card-body text-dark">
      <h4>New Character for <%= @story.short_title %></h4>
      <%= render 'form', character: @character, post_url: story_characters_path(@story) %>
      <div class="btn-group p-2">
        <%= link_to t('show_story'), back_to_story_path(@story.id), class: "btn btn-sm btn-outline-dark" %>
        <%= link_to "All characters", story_characters_path(@story), class: "btn btn-sm btn-outline-dark" %> 
      </div>
    </div>
  </div>
</div>