config/routes.rb
Rails.application.routes.draw do
  pages = %w(about terms privacy_policy)

  resources :stories, except: :show, shallow: true do
    resources :chapters, except: [:index, :show], shallow: true do
      resources :parts, except: :index, shallow: true do
        resources :posts, except: [:show, :index] 
      end  
    end
    resources :characters, except: :show
  end

  root 'pages#index'
  pages.each do |page|
    get "#{page}", to: "pages##{page}"
  end
  resources :pages, only: [:edit, :update, :show]
  post 'tinymce_assets', to: 'tinymce_assets#create'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :settings, only: [:new, :create, :edit, :update]
  # get 'import', to: 'import#index'
  # post 'process', to: 'import#add_data'

end

app/models/chapter.rb
class Chapter < ApplicationRecord
  belongs_to :story
  has_many :parts, dependent: :destroy
  accepts_nested_attributes_for :parts, allow_destroy: true

  validates :title, presence: true
  validates :sort_order, numericality: true, uniqueness: { scope: :story_id, message: "This sort # has already been chosen." }

  default_scope { order(sort_order: :asc) }

  scope :next_chapter, -> (story_id, sort_order) { where(
    "chapters.story_id = :story_id AND chapters.sort_order > :sort_order", 
    {story_id: story_id, sort_order: sort_order}).limit(1)}

  scope :prev_chapter, -> (story_id, sort_order) { unscope(:order).where(
      "chapters.story_id = :story_id AND chapters.sort_order < :sort_order", 
      {story_id: story_id, sort_order: sort_order}).order(sort_order: :desc).limit(1)}
  
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  before_action :require_admin_user
  before_action :set_story, only: [ :new, :create ]
  before_action :set_chapter, only: [ :edit, :update, :destroy ]
   
  def edit
  end

  def new
    @chapter = @story.chapters.new
  end

  def create
    @chapter = @story.chapters.build( chapter_params )
    if @chapter.save
      flash[:notice] = "The chapter was successfully created"
      redirect_to back_to_story_path(@story.id)
    else
      render :new
    end
  end

  def update
    if @chapter.update( chapter_params )
      flash[:notice] = "The chapter was successfully updated"
      redirect_to back_to_story_path(@story.id)
    else
      render :edit
    end
  end

  def destroy
    @chapter.destroy
    flash[:notice] = "The chapter was successfully deleted"
    redirect_to back_to_story_path(@story.id)
  end

  private
    def set_story
      @story = Story.find(params[:story_id])
    end

    def set_chapter
      @chapter = Chapter.find(params[:id])
      @story = Story.find(@chapter.story_id)
    end

    def chapter_params
      params.require(:chapter).permit(:title, :subtitle, :sort_order)
    end

end

app/views/chapters/_form.html.erb
<%= form_with( model: chapter, url: post_url ) do |form| %>
  <%= render 'shared/error_messages', resource: chapter %>
  <div class="row">
    <div class="col-2 d-flex align-items-center">
      <%= form.label :sort_order %>
    </div>
    <div class="col field form-group">
      <%= form.number_field :sort_order, class: "form-control" %>
    </div>
  </div>

  <div class="row pt-2">
    <div class="col-2 d-flex align-items-center">
      <%= form.label :title %>
    </div>
    <div class="col field form-group">
      <%= form.text_field :title, class: "form-control" %>
    </div>
  </div>
  <div class="row pt-2">
    <div class="col-2 d-flex align-items-center">
      <%= form.label :subtitle %>
    </div>
    <div class="col field form-group">
      <%= form.text_field :subtitle, class: "form-control" %>
    </div>
  </div>  
  <div class="actions pt-2">
    <%= form.submit class: "btn btn-sm btn-outline-dark" %>
  </div>
<% end %>

app/views/chapters/edit.html.erb
<div class="container py-3">
  <div class="card mb-3 shadow-lg rounded border">
    <div class="card-body text-dark">
      <h4>Editing chapter for <%= @story.short_title %></h4>
      <%= render 'form', chapter: @chapter, post_url: chapter_path(@chapter) %>
      <div class="btn-group p-2">
        <%= link_to "Delete", chapter_path(@chapter), class: "btn btn-sm btn-outline-dark", 
                    method: :delete, 
                    data: { confirm: "Are you sure? This will delete ALL chats, parts from this chapter too." } %>
        <%= link_to t('show_story'), back_to_story_path(@story.id), class: "btn btn-sm btn-outline-dark" %> 
      </div>
    </div>
  </div>
</div>

app/views/chapters/new.html.erb
<div class="container py-3">
  <div class="card mb-3 shadow-lg rounded border">
    <div class="card-body text-dark">
      <h4>New chapter for <%= @story.short_title %></h4>
      <%= render 'form', chapter: @chapter, post_url: story_chapters_path(@story) %>
      <div class="btn-group p-2">
        <%= link_to t('show_story'), back_to_story_path(@story.id), class: "btn btn-sm btn-outline-dark" %> 
      </div>
    </div>
  </div>
</div>