config/routes.rb
Rails.application.routes.draw do
  pages = %w(about terms privacy_policy)

  resources :stories, except: :show, shallow: true do
    resources :chapters, except: [:index, :show], shallow: true do
      resources :parts, except: :index, shallow: true do
        resources :posts, except: [:show, :index] 
      end  
    end
    resources :characters, except: :show
  end

  root 'pages#index'
  pages.each do |page|
    get "#{page}", to: "pages##{page}"
  end
  resources :pages, only: [:edit, :update, :show]
  post 'tinymce_assets', to: 'tinymce_assets#create'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :settings, only: [:new, :create, :edit, :update]
  # get 'import', to: 'import#index'
  # post 'process', to: 'import#add_data'

end

app/views/layouts/_footer.html.erb
<!-- text-center mt-auto /-->
<footer class="mt-auto small footer">
  <div class="container-fluid dark-footer">

    <div class="row p-1">
      <div class="col text-center">
        <a href="mailto:mic@micstories.com" class="text-dark-footer">mic@micstories.com</a>
      </div>
      <div class="col text-center">
        <%= link_to "Terms & Conditions", terms_path, class: "text-dark-footer" %>
      </div>
      <div class="col text-center">
        <%= link_to "Privacy Policy", privacy_policy_path, class: "text-dark-footer" %>
      </div>
    </div>
    <div class="row pb-2" style="font-size:8pt">
      <div class="col text-start">
        © 2022 Copyright:
        <a class="text-dark-footer" href="\">micstories.com</a>
      </div>
      <div class="col text-end">
        Developed by: 
        <a href="" class="text-dark-footer">NTR Computer Services</a>
      </div>
    </div>
  </div>

  <div class="container-fluid text-center bg-light" >
    <div class="row">
      <div class="col-3 p-1 d-flex justify-content-center">
        <img alt="Creative Commons License" src="https://i.creativecommons.org/l/by-nc-nd/3.0/us/88x31.png">
      </div>
      <div class="col align-self-center text-start light-footer">
        All text is the property of the author.<br/>
        <a href="https://creativecommons.org/licenses/by-nc-nd/3.0/us/" class="text-light-footer">
          This work is licensed under a Creative Commons Attribution-Noncommercial-No Derivative Works 3.0 United States License
        </a>
     </div>
    </div>
 </div>

</footer>

app/views/layouts/_messages.html.erb
<div class="container pt-3">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">     
      <%= msg %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<!-- 025328 __ //-->
<nav class="navbar navbar-expand-lg navbar-dark navbar-bg">
  <div class="container-fluid">
    <%= link_to "Mic Stories", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mx-auto mb-2 mb-lg-0 justify-content-end">
        <li class="nav-item">
          <%= link_to "About", about_path, class: "#{request.path == about_path  ? "nav-link active" : "nav-link"}" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Stories
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <% item_in_list = false %>
            <% @stories.each do |story| %>
              <% if story.published %>
                <li>
                  <%= link_to story.short_title, back_to_story_path(story.id), class: "dropdown-item" %>
                </li>
                <% item_in_list = true %>
              <% elsif admin_user? %>
                <li>
                  <%= link_to back_to_story_path(story.id), class: "dropdown-item unpublished-nav-item" do %>
                    <i class="bi bi-braces-asterisk"></i> <%= story.short_title %>
                  <% end %>
                </li>
                <% item_in_list = true %>
              <% end %>
            <% end %>
            <% if !item_in_list %>
              <li> No Stories </li>
            <% end %>
            <% if admin_user? %>
              <li><hr class="dropdown-divider"></li>
              <li>
                <%= link_to new_story_path, class: "dropdown-item" do %>
                  <i class="bi bi-journal-plus"></i> New Story
                <% end %>
              </li>
            <% end %>
          </ul>
        </li>
        <% if admin_user? %>
        <li class="nav-item">
          
          <%= link_to "Settings", get_settings_path, class: "#{request.path == get_settings_path  ? "nav-link active" : "nav-link"}" %>
        </li>
        <% end %>
      </ul>
      <ul class="navbar-nav ml-auto p-1">
        <li class="nav-item">
          <a class="nav-link active" href="mailto:mic@micstories.com">mic@micstories.com</a>            
        </li>
        <% if logged_in? %>
          <li class="nav-item ps-2">
            <%= link_to "Logout", logout_path, class: "btn btn-sm btn-outline-light", method: :delete %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-100">
  <head>
    <title>
    <%= if content_for?(:title) then yield(:title) + ' | ' end %>
    Mic's Stories </title>
    <% if get_meta_description.present? %>
      <meta name="description" content="<%= get_meta_description %>">
    <% end %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta charset="UTF-8">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= tinymce_assets %>
    <!-- , 'data-turbolinks-track': 'reload' //-->
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body class="d-flex flex-column h-100">
    <main class="flex-shrink-0">
      <%= render 'layouts/navbar' %>
      <%= render 'layouts/messages' %>
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>